baseURL = "https://ngoldbaum.github.io/"
languageCode = "en-us"
title = "Nathan Goldbaum"
theme = ['hugo-shortcode-roneo-collection', "slick"]
pygmentsCodeFences = true

[params]
    custom_css = ["assets/custom.css"]

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  pageRef = "/about"

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"

  [[menu.main]]
  identifier = "resume"
  name = "Résumé"
  url = "/cv.pdf"