baseURL = "https://ngoldbaum.github.io/"
languageCode = "en-us"
title = "Nathan Goldbaum"
theme = "slick"
pygmentsCodeFences = true

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/"

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"

  [[menu.main]]
  identifier = "resume"
  name = "Résumé"
  url = "/cv.pdf"